### ISSUE TITLE
ClojureScript >=1.11.51 seems to break Rum

### ISSUE THREAD

**Issue by jwr** [tonsky/rum#253] opened 2022-06-20 09:07 UTC
Switching from ClojureScript 1.11.4 to 1.11.51 breaks my Rum app. I'm having a hard time making sense of the errors, but it appears as if args passed to components are not the same args that the component receives. For example, in a three-arg component first two are missing, the third arg becomes the first one, and subsequent ones are nil.

The resulting errors are like `Objects are not valid as a React child (found: object with keys {ns, name, fqn, _hash, cljs$lang$protocol_mask$partition0$, cljs$lang$protocol_mask$partition1$}). `, because a hiccup vector was expected, but something else (keyword? symbol?) was used instead.

I verified that just switching the ClojureScript version is enough to trigger the problem in multiple places.

**Comment by tonsky** [comment] 2022-06-20 17:05
This should fix it once merged https://clojure.atlassian.net/browse/CLJS-3382

**Comment by jwr** [comment] 2022-06-21 06:20
Thank you for the really quick response, investigation, and potential fix!

(I'm curious though, it's been five weeks since 1.11.51 was released, and nobody noticed?)

**Comment by tonsky** [comment] 2022-06-21 11:47
I had hard time reproducing it outside of Rum, not sure why. Looks like it’s an edge case. Rum reproduces it 100% though

**Comment by jwr** [comment] 2022-06-24 09:53
ClojureScript 1.11.60 has the fix and Rum works again with this version. Thank you!

**Closed as completed** 2022-06-24 14:23 UTC
