### ISSUE TITLE
server side render inconsistency: excessive space in class when set as attribute list

### ISSUE THREAD

**Issue by altV** [tonsky/rum#119] opened 2017-02-06 11:35 UTC
[:a.hi {:class [nil]}] gives
`<a class="hi ">` in server case, and
`<a class="hi">` on client. (or maybe vice versa)

**Comment by tonsky** [comment] 2017-02-06 12:33
Description is broken. Maybe a duplicate of #104 though

**Comment by altV** [comment] 2017-02-06 12:35
oops. patched

**Comment by altV** [comment] 2017-02-06 12:36
looks like a duplicate. will bump my version from 0.10.7 to 0.10.8 and retest, but changelog doesn't tell about this one

**Comment by tonsky** [comment] 2017-02-06 12:41
It’s because it’s only partially fixed :)

**Comment by roman01la** [comment] 2020-04-14 12:53
Closing, because it's a duplicate.

**Closed as completed by roman01la** 2020-04-14 12:53 UTC
