### ISSUE TITLE
State manipulation in :did-mount seems to have no effect

### ISSUE THREAD

**Issue by chbrown** [tonsky/rum#117] opened 2017-01-27 00:39 UTC
In particular, I'm looking for a similar solution to the basic `(defcs time-label ...)` example from the README:

    (rum/defcs time-label < { :did-mount (fn [state]
                                           (assoc state ::time (js/Date.))) }
      [state label]
      [:div label ": " (::time state)])

The README doesn't say what that's supposed to render to, but I thought I'd get a div with something like `(value of label): Thu Jan 26 2017 18:33:20 GMT-0600 (CST)`.

Instead, it doesn't seem to do anything.

Here's an example: <https://chbrown.github.io/rum-did-mount/resources/public/>

Sorry if an entire repo is overkill for a MWE; I just wanted to make sure it was clear from bottom to top. The [repo](https://github.com/chbrown/rum-did-mount) contains five files total; here are the source files:

* [`project.clj`](https://github.com/chbrown/rum-did-mount/blob/master/project.clj)
* [`resources/public/index.html`](https://github.com/chbrown/rum-did-mount/blob/master/resources/public/index.html)
* [`src/rum_did_mount/core.cljs`](https://github.com/chbrown/rum-did-mount/blob/master/src/rum_did_mount/core.cljs)

Am I using `state` wrong? Or mounting my component tree wrong?

**Comment by tonsky** [comment] 2017-01-27 06:06
try `(str (::time state))`

**Comment by tonsky** [comment] 2017-01-27 06:07
oh, sorry. `did-mount` happens after rendering, as the name implies. Change to `will-mount`

**Comment by chbrown** [comment] 2017-01-27 06:11
Right, okay, so that example in the README is misleading, as I've discovered reading the source since creating the issue, but more generally I need to hook into a post-render phase. I'm measuring SVG Text to get its BBox, and in :will-render, as you'd expect, `(rum/dom-node state)` is null.

**Comment by chbrown** [comment] 2017-01-27 06:23
Did not mean to click that.

Anyhow, looking at the React lifecycle docs, https://facebook.github.io/react/docs/react-component.html#componentdidmount, it seems like it's quite common to set state in `componentDidMount`. 

> componentDidMount() is invoked immediately after a component is mounted. Initialization that requires DOM nodes should go here. If you need to load data from a remote endpoint, this is a good place to instantiate the network request. Setting state in this method will trigger a re-rendering.

So I'd expect that, since I'm supposed to return the given state in my `:did-mount` handler, if I return a changed state, it'd trigger a render.

For now, I'm calling `(-> state :rum/react-component rum/request-render)` as the first form in my `:did-mount` handler body, and then going about my BBox logic, eventually returning state. But what is the point of returning state at all? Just to have the variable updated in the component? Is there a way to say "whenever I `vswap!` on `state` for anything (or keys x, y, z), re-render"?

I was also surprised there's only one call to `(.setState component ...)` in the entire rum codebase (in the `componentWillReceiveProps` implementation)! In my plain-JS endeavors I use `setState` quite a bit. Probably more than I ought, but still, is there a general philosophical stance that Rum holds against `setState`? Like, Rum avoids interacting with React's internal state because CLJS/Rum (with volatiles, atoms, etc.) can do it better?

Thanks for Rum, and thanks in advance for any preferable design pattern suggestions that would put me on a higher path.

**Comment by rauhs** [comment] 2017-01-27 06:35
@chbrown FYI: Using string refs is considered legacy, you should not use it in new code anymore. I'd even vote for Rum to make the `dom-node` functions deprecated. More info:
- https://facebook.github.io/react/docs/refs-and-the-dom.html 
- http://stackoverflow.com/questions/37468913/why-ref-string-is-legacy

They'll eventually be removed from React from what I've heard.

**Comment by chbrown** [comment] 2017-01-27 06:41
@rauhs I don't like using them, and I usually don't need to, but it comes down to this: how else am I going to measure how wide my text comes out to? Obviously, reading render/visual-stage values from the DOM isn't React's strong point, but I want to use React for everything else, and just need this slight kludge to get my work done.

**Comment by tonsky** [comment] 2017-01-27 07:21
@chbrown Rum decouples storing stuff in state and requesting re-render. These are two different activities, and you’re free to use one of them without forcing another. Or both, if you’d like. In React, if you want to store e.g. timer handle in a state, that would trigger a re-render, and if I don’t need that, I’m out of luck. Or if you want to trigger a re-render, you’d do `this.setState(this.state)` which anything but not a beatiful API. It obscures the intent.

Rum is not mapped to React API one-to-one. It offers its own API, with its own semantics, which (I hope) is cleaner, better, suits ClojureScript style of code (FP, pure functions, immutable values) better. We have state, mixins, component but they have different meaning in Rum and work differently. Sorry if that did mislead you, it might be confusing esp. if you have strong React background.

**Comment by tonsky** [comment] 2017-01-27 07:24
There’s also a video explaining why Rum was designed that way. If you’re interested in it, it might be a good starting point, you’ll better understand the angle I expect people would look at Rum at. Here’s it https://www.youtube.com/watch?v=2fLx4fu9VV8

**Comment by roman01la** [comment] 2020-04-14 12:51
Looks like the question was answered. Closing this.

**Closed as completed by roman01la** 2020-04-14 12:51 UTC
Labels: question
