### ISSUE TITLE
looking up a class from a map pulls the map into the rendered component's class attribute

### ISSUE THREAD

**Issue by OliverM** [tonsky/rum#97] opened 2016-09-09 10:34 UTC
If I define a map of styles like so:

``` clj
(def csslib
      {:table-header-row "bg-mid-gray"
       :table-header-cell "bg-yellow"
       :table-row "bg-red"
       :table-cell "bg-blue"
    })
```

and then try to refer to them as class attributes in a `defc` call like so:

``` clj
(r/defc table-cell < r/static [{:keys [text] :as cell}]
   [:td {:class (:table-cell csslib)}
    [:span text]])
```

The assigned class for the table cell in the generated html reads

``` html
class="table-cell :table-header-row bg-mid-gray :table-header-cell bg-yellow :table-row bg-red :table-cell bg-blue"
```

A workaround is to put the map lookup inside a `str` call, which gives the expected class attribute of `class="bg-blue"` in the rendered html.

**Comment by martinklepsch** [comment] 2016-09-09 11:05
I think the issue isn't with Rum here but with [Sablono](https://github.com/r0man/sablono). In contrast the following works:

``` clojure
(get csslib :table-cell)
(-> csslib :table-cell)
(csslib :table-cell)
```

If I understand the code correcty this can only be caused by `sablono.util/join-classes` but I don't understand how it happens yet.

If you can confirm the above please open an issue on Sablono as well.

**Comment by OliverM** [comment] 2016-09-09 11:33
@martinklepsch they work, thanks! I've [filed an issue](https://github.com/r0man/sablono/issues/130) on Sablono as you suggested

**Comment by tonsky** [comment] 2016-09-09 21:44
Ha! Looks like Sablono thinks it’s a list, not a function call. Probably some macro pre-compilation issue

**Comment by r0man** [comment] 2016-10-03 12:26
I added a fix for this problem. It's in sablono `0.7.5`.

**Comment by tonsky** [comment] 2016-10-03 12:49
Checked, seems to work. Thanks, @r0man!

**Closed as completed by tonsky** 2016-10-03 12:49 UTC
